# ~/.tmux.conf

###########################################################################
# Remap prefix from default (C-b) to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

###########################################################################
# General options

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Enable OSC 52 clipboard support for sharing clipboard over SSH
set -g set-clipboard on
set -sa terminal-features ',xterm-256color:clipboard'
# - When you select and copy text in tmux's copy mode, tmux itself emits OSC52
#   escape sequences to your terminal.
# - Assuming your terminal supports it (e.g., iTerm2, ghostty), it receives the
#   OSC52 sequence and writes it to your local macOS clipboard.
# - This works over SSH because OSC52 travels through the SSH connection back
#   to your local terminal. There's no special clipboard protocol involved. It's
#   just terminal output.
# NOTE: before tmux 3.3 there were some issues with this so we need the tmux-yank plugin

# scrollback size
set -g history-limit 50000

# pass through xterm keys (allow ctrl left, right etc)
set -g xterm-keys on

# Use vim like keys
# for tmux-yank
set -g @shell_mode 'vi'
set -g mode-keys vi

# If on a OLDER Mac...
# if-shell 'test "$(uname -s)" = Darwin' 'set-option -g default-command "exec reattach-to-user-namespace -l bash"'

# enable mouse scrolling
set -g mouse on

###########################################################################
# General keymap

# reload tmux config
unbind r
bind r \
    source-file ~/.tmux.conf \;\
    display 'Reloaded tmux config.'

# fzf window switcher
bind C-t run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/window.sh switch"

# open panes in current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

###########################################################################
# Plugins
# To install plugins:  prefix + I
# To update plugins:   prefix + U
# To remove plugins:   prefix + alt + u  (removes unlisted plugins)

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'
# Theme
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'double/cyan'
# Share clipboard with system
set -g @plugin 'tmux-plugins/tmux-yank'
# Fuzzy finder integration
set -g @plugin 'sainnhe/tmux-fzf'
# Sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'

# start the plugin manager, must be at bottom of conf file
run '~/.tmux/plugins/tpm/tpm'
