[directory]
truncate_to_repo=false

[git_branch]
style="bold blue"

[git_status]
style="bold white"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

conflicted = "[=${count}](bright-red)"

untracked = "[?${count}](bright-blue)"

stashed = "[\\$${count}](cyan)"

modified = "[!${count}](bright-red)"

staged = "[+${count}](green)"

renamed = "[»${count}](bright-red)"

deleted = "[✘${count}](bright-red)"

[nodejs]
disabled=true
