[directory]
truncate_to_repo=false

[git_branch]
style="bold blue"

[git_status]
style="bold white"
ahead = "⇡${count}"
behind = "⇣${count}"

diverged = "⇕⇡${ahead_count}⇣${behind_count}"
diverged.style="bright-red"

conflicted = "=${count}"
conflicted.style="bright-red"

untracked_count.enabled=true
untracked_count.style="bright-blue"
untracked = "?${count}"
untracked.style="bright-blue"

stashed_count.enabled=true
stashed_count.style="cyan"
stashed.style="cyan"

modified_count.enabled=true
modified_count.style="bright-red"
modified.style="bright-red"

staged_count.enabled=true
staged_count.style="green"
staged.style="green"
# A renamed file has been added to the staging area.
renamed.style="bright-red"
# A file's deletion has been added to the staging area.
deleted.style="bright-red"

[nodejs]
disabled=true
