castwide.solargraph
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
eg2.tslint
esbenp.prettier-vscode
fabianlauer.vs-code-xml-format
fabiospampinato.vscode-todo-plus
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
ms-python.python
ms-vscode.autorest
ms-vsliveshare.vsliveshare
naco-siren.gradle-language
paulmolluzzo.convert-css-in-js
PeterJausovec.vscode-docker
rebornix.Ruby
robinbentley.sass-indented
streetsidesoftware.code-spell-checker
vscodevim.vim
